Update build.rb
Fix for:
/Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/lib/staticmatic/mixins/build.rb:7:in `block in build': undefined method `mappings' for Tilt:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/lib/staticmatic/mixins/build.rb:4:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/lib/staticmatic/mixins/build.rb:4:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/lib/staticmatic/base.rb:75:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/bin/staticmatic:71:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/staticmatic2-2.1.8/bin/staticmatic:142:in `<top (required)>'
	from /usr/bin/staticmatic:23:in `load'
	from /usr/bin/staticmatic:23:in `<main>'